apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clustergate.labels" . | nindent 4 }}
    {{- include "hpe-ezua.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "clustergate.databaseUrl" . | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
  METRICS_SECRET: {{ .Values.backend.secrets.metricsSecret | quote }}
  POSTGRES_USER: {{ .Values.postgres.credentials.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
